[project]
name = "garmin-to-notion"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "garminconnect>=0.2.25",
    "notion-client>=2.3.0",
    "pydantic>=2.11.1",
    "pydantic-extra-types>=2.10.3",
    "pytz>=2025.2",
]
